include ../theos/makefiles/common.mk

TWEAK_NAME = ti_tweak
ti_tweak_FILES = Tweak.xm
ti_tweak_SUBPROJECTS = shared

TOOL_NAME = ti_tool
ti_tool_FILES = tool.mm
ti_tool_SUBPROJECTS = shared

include $(FW_MAKEDIR)/tweak.mk
include $(FW_MAKEDIR)/tool.mk
