# A tweak which implements the SBIcon subclass
TWEAK_NAME = logos_subclass
logos_subclass_FILES = Tweak.xm
logos_subclass_FRAMEWORKS = UIKit

# An application bundle that uses that SBIcon subclass
BUNDLE_NAME = LogosSubclass
LogosSubclass_BUNDLE_EXTENSION = app
LogosSubclass_INSTALL_PATH = /Applications

include ../theos/makefiles/common.mk
include $(FW_MAKEDIR)/tweak.mk
include $(FW_MAKEDIR)/bundle.mk
